name: Clean Deployments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to clean up (e.g., Production, Integration)'
        required: true
        type: string
        default: 'Integration'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 🗑 Delete deployment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          onlyRemoveDeployments: true
